[build]
  publish = "public"
  command = "hugo --gc --minify --enableGitInfo"

[context.production.environment]
  HUGO_VERSION = "0.116.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
