[build]
  command = "hugo --gc --minify --enableGitInfo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.125.3"

[[redirects]]
  from = "https://www.mestskafarmaba.sk/*"
  to = "https://mestskafarmaba.sk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com; style-src 'self' 'unsafe-inline';"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
