backend:
  name: github
  repo: tvoje-username/moj-web
  branch: main
  base_url: https://tvoje-github-username.github.io
  auth_type: implicit
  app_id: TVOJE_GITHUB_APP_ID

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
