backend:
  name: github
  repo: garubasro/MestskaFarmaBA
  branch: main
  auth_type: implicit
  client_id: Ov23liRCVaNwngQwndXO

media_folder: "static/img"
public_folder: "/img"
publish_mode: simple



collections:
  - name: "post"
    label: "Post"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    path: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "post/{{slug}}"
    media_folder: "static/img/posts"
    public_folder: "/img/posts"
    fields:
      - label: "Title:"
        name: "title"
        widget: "string"
        required: true
      - label: "Subtitle:"
        name: "subtitle"
        widget: "string"
      - label: "Excerpt:"
        name: "excerpt"
        widget: "string"
      - label: "Description:"
        name: "description"
        widget: "string"
      - label: "Date:"
        name: "date"
        widget: "datetime"
        default: ""
      - label: "Author:"
        name: "author"
        widget: "string"
        default: "Pavol"
      - label: "Image:"
        name: "image"
        widget: "image"
        choose_url: false
        media_library:
          config:
            multiple: false
      - label
