backend:
  name: github
  repo:  garubasro/MestskaFarmaBA 
  branch: main
  auth_type: implicit
  app_id: Ov23liCnJpmJAjUB95e9

media_folder: "static/img"
public_folder: "/img"
publish_mode: editorial_workflow


collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
