backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

site_url: https://mestskafarmaba.sk
display_url: https://mestskafarmaba.sk

collections:
  - name: "post"
    label: "Poss"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
